.TH "src Directory Reference" 3 "Thu Feb 6 2014" "Version 0.7.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdatastore\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcallbacks\&.h\fP"
.br
.RI "\fIFunctions to set application's callbacks\&. \fP"
.ti -1c
.RI "file \fBcallbacks_ssh\&.h\fP"
.br
.RI "\fIFunctions to set libssh2's callbacks\&. \fP"
.ti -1c
.RI "file \fBdatastore\&.h\fP"
.br
.RI "\fINETCONF datastore handling function prototypes and structures\&. \fP"
.ti -1c
.RI "file \fBdatastore_xml\&.h\fP"
.br
.RI "\fINETCONF datastore handling function prototypes and structures - XML variants\&. \fP"
.ti -1c
.RI "file \fBerror\&.h\fP"
.br
.RI "\fINETCONF error handling functions\&. \fP"
.ti -1c
.RI "file \fBlibnetconf\&.h\fP"
.br
.RI "\fIlibnetconf's main header\&. \fP"
.ti -1c
.RI "file \fBlibnetconf_ssh\&.h\fP"
.br
.RI "\fIlibnetconf's header for control libssh2\&. \fP"
.ti -1c
.RI "file \fBlibnetconf_xml\&.h\fP"
.br
.RI "\fIlibnetconf's main header for libxml2 variants of some functions\&. \fP"
.ti -1c
.RI "file \fBmessages\&.h\fP"
.br
.RI "\fIFunctions to create NETCONF messages\&. \fP"
.ti -1c
.RI "file \fBmessages_xml\&.h\fP"
.br
.ti -1c
.RI "file \fBnetconf\&.h\fP"
.br
.RI "\fIlibnetconf's general public functions and structures definitions\&. \fP"
.ti -1c
.RI "file \fBnotifications\&.h\fP"
.br
.RI "\fIFunctions to handle NETCONF Notifications\&. \fP"
.ti -1c
.RI "file \fBnotifications_xml\&.h\fP"
.br
.RI "\fINETCONF Notifications functions with libxml2 support\&. \fP"
.ti -1c
.RI "file \fBsession\&.h\fP"
.br
.RI "\fIFunctions to handle NETCONF sessions\&. \fP"
.ti -1c
.RI "file \fBssh\&.h\fP"
.br
.RI "\fIFunctions to connect to NETCONF server via SSH2\&. \fP"
.ti -1c
.RI "file \fBtransapi\&.h\fP"
.br
.ti -1c
.RI "file \fBurl\&.h\fP"
.br
.RI "\fIlibnetconf's public API to use the URL capability\&. \fP"
.ti -1c
.RI "file \fBwith_defaults\&.h\fP"
.br
.RI "\fIImplementation of NETCONF's with-defaults capability defined in RFC 6243\&. \fP"
.in -1c
