.TH "src/transapi Directory Reference" 3 "Wed Apr 3 2013" "Version 0.4.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/transapi Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtransapi\&.h\fP"
.br
.ti -1c
.RI "file \fBxmldiff\&.h\fP"
.br
.ti -1c
.RI "file \fByinparser\&.h\fP"
.br
.in -1c
