.TH "src/datastore/custom Directory Reference" 3 "Thu Feb 6 2014" "Version 0.7.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/datastore/custom Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdatastore_custom\&.h\fP"
.br
.RI "\fINETCONF datastore handling function prototypes and structures for custom datastore implementation\&. \fP"
.in -1c
