.TH "deprecated" 3 "Thu Nov 27 2014" "Version 0.9.0-9" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBGlobal \fBncds_apply_rpc\fP (ncds_id id, const struct nc_session *session, const nc_rpc *rpc)\fP" 1c
Function will be removed in version 1\&.0\&.0, use \fBncds_apply_rpc2all()\fP instead\&.
.PP

