.TH "src/error.h" 3 "Thu Feb 6 2014" "Version 0.7.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/error.h \- 
.PP
NETCONF error handling functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'netconf\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNC_ERR\fP { \fBNC_ERR_EMPTY\fP, \fBNC_ERR_IN_USE\fP, \fBNC_ERR_INVALID_VALUE\fP, \fBNC_ERR_TOO_BIG\fP, \fBNC_ERR_MISSING_ATTR\fP, \fBNC_ERR_BAD_ATTR\fP, \fBNC_ERR_UNKNOWN_ATTR\fP, \fBNC_ERR_MISSING_ELEM\fP, \fBNC_ERR_BAD_ELEM\fP, \fBNC_ERR_UNKNOWN_ELEM\fP, \fBNC_ERR_UNKNOWN_NS\fP, \fBNC_ERR_ACCESS_DENIED\fP, \fBNC_ERR_LOCK_DENIED\fP, \fBNC_ERR_RES_DENIED\fP, \fBNC_ERR_ROLLBACK_FAILED\fP, \fBNC_ERR_DATA_EXISTS\fP, \fBNC_ERR_DATA_MISSING\fP, \fBNC_ERR_OP_NOT_SUPPORTED\fP, \fBNC_ERR_OP_FAILED\fP, \fBNC_ERR_MALFORMED_MSG\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct nc_err * \fBnc_err_dup\fP (const struct nc_err *error)"
.br
.RI "\fIDuplicate an error description structure\&. \fP"
.ti -1c
.RI "void \fBnc_err_free\fP (struct nc_err *err)"
.br
.RI "\fIFree NETCONF error structure\&. \fP"
.ti -1c
.RI "const char * \fBnc_err_get\fP (const struct nc_err *err, \fBNC_ERR_PARAM\fP param)"
.br
.RI "\fIGet value of the specified parameter of the NETCONF error structure\&. \fP"
.ti -1c
.RI "struct nc_err * \fBnc_err_new\fP (\fBNC_ERR\fP error)"
.br
.RI "\fICreate a new error description structure\&. \fP"
.ti -1c
.RI "int \fBnc_err_set\fP (struct nc_err *err, \fBNC_ERR_PARAM\fP param, const char *value)"
.br
.RI "\fISet selected parameter of the NETCONF error structure to the specified value\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
NETCONF error handling functions\&. 


.PP
\fBAuthor:\fP
.RS 4
Radek Krejci rkrejci@cesnet.cz Copyright (c) 2012-2014 CESNET, z\&.s\&.p\&.o\&.
.RE
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of the Company nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
ALTERNATIVELY, provided that this notice is retained in full, this product may be distributed under the terms of the GNU General Public License (GPL) version 2 or later, in which case the provisions of the GPL apply INSTEAD OF those given above\&.
.PP
This software is provided ``as is, and any express or implied warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose are disclaimed\&. In no event shall the company or contributors be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this software, even if advised of the possibility of such damage\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNC_ERR\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINC_ERR_EMPTY \fP\fP
.TP
\fB\fINC_ERR_IN_USE \fP\fP
.TP
\fB\fINC_ERR_INVALID_VALUE \fP\fP
.TP
\fB\fINC_ERR_TOO_BIG \fP\fP
.TP
\fB\fINC_ERR_MISSING_ATTR \fP\fP
.TP
\fB\fINC_ERR_BAD_ATTR \fP\fP
.TP
\fB\fINC_ERR_UNKNOWN_ATTR \fP\fP
.TP
\fB\fINC_ERR_MISSING_ELEM \fP\fP
.TP
\fB\fINC_ERR_BAD_ELEM \fP\fP
.TP
\fB\fINC_ERR_UNKNOWN_ELEM \fP\fP
.TP
\fB\fINC_ERR_UNKNOWN_NS \fP\fP
.TP
\fB\fINC_ERR_ACCESS_DENIED \fP\fP
.TP
\fB\fINC_ERR_LOCK_DENIED \fP\fP
.TP
\fB\fINC_ERR_RES_DENIED \fP\fP
.TP
\fB\fINC_ERR_ROLLBACK_FAILED \fP\fP
.TP
\fB\fINC_ERR_DATA_EXISTS \fP\fP
.TP
\fB\fINC_ERR_DATA_MISSING \fP\fP
.TP
\fB\fINC_ERR_OP_NOT_SUPPORTED \fP\fP
.TP
\fB\fINC_ERR_OP_FAILED \fP\fP
.TP
\fB\fINC_ERR_MALFORMED_MSG \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
