.TH "General functions" 3 "Fri Apr 20 2012" "Version 0.1.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
General functions \- 
.PP
libnetconf's miscellaneous functions\&.  

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNC_VERB_LEVEL\fP { \fBNC_VERB_ERROR\fP, \fBNC_VERB_WARNING\fP, \fBNC_VERB_VERBOSE\fP, \fBNC_VERB_DEBUG\fP }"
.br
.RI "\fIVerbosity levels\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnc_verbosity\fP (\fBNC_VERB_LEVEL\fP level)"
.br
.RI "\fISet libnetconf's verbosity level\&. \fP"
.ti -1c
.RI "void \fBnc_callback_print\fP (int(*func)(const char *msg))"
.br
.RI "\fISet callback function for printing libnetconf's messages\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libnetconf's miscellaneous functions\&. 


.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNC_VERB_LEVEL\fP"

.PP
Verbosity levels\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fINC_VERB_ERROR \fP\fP
Print only error messages\&. 
.TP
\fB\fINC_VERB_WARNING \fP\fP
Print error and warning messages\&. 
.TP
\fB\fINC_VERB_VERBOSE \fP\fP
Besides errors and warnings, print some other verbose messages\&. 
.TP
\fB\fINC_VERB_DEBUG \fP\fP
Print all messages including some development debug messages\&. 
.PP
Definition at line 138 of file netconf\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBnc_verbosity\fP (\fBNC_VERB_LEVEL\fPlevel)"

.PP
Set libnetconf's verbosity level\&. \fBParameters:\fP
.RS 4
\fIlevel\fP Enabled verbosity level (includes all levels with higher priority)\&. 
.RE
.PP

.SS "void \fBnc_callback_print\fP (int(*)(const char *msg)func)"

.PP
Set callback function for printing libnetconf's messages\&. \fBParameters:\fP
.RS 4
\fIfunc\fP Callback function to use\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
