.TH "src/libnetconf_tls.h" 3 "Fri Apr 15 2016" "Version 0.10.0-146_trunk" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libnetconf_tls.h \- 
.PP
libnetconf's header for control openssl\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <openssl/ssl\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include 'netconf\&.h'\fP
.br
\fC#include 'transport\&.h'\fP
.br
\fC#include 'callhome\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct nc_session * \fBnc_session_accept_tls\fP (const struct nc_cpblts *capabilities, const char *username, SSL *tls_sess)"
.br
.ti -1c
.RI "void \fBnc_tls_destroy\fP (void)"
.br
.RI "\fIDestroy all resources allocated for preparation of TLS connections\&. \fP"
.ti -1c
.RI "int \fBnc_tls_init\fP (const char *peer_cert, const char *peer_key, const char *CAfile, const char *CApath, const char *CRLfile, const char *CRLpath)"
.br
.RI "\fISet paths to the client certificate and its private key\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libnetconf's header for control openssl\&. 


.PP
\fBAuthor:\fP
.RS 4
Radek Krejci rkrejci@cesnet.cz Copyright (c) 2012-2014 CESNET, z\&.s\&.p\&.o\&.
.RE
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of the Company nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
ALTERNATIVELY, provided that this notice is retained in full, this product may be distributed under the terms of the GNU General Public License (GPL) version 2 or later, in which case the provisions of the GPL apply INSTEAD OF those given above\&.
.PP
This software is provided ``as is, and any express or implied warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose are disclaimed\&. In no event shall the company or contributors be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this software, even if advised of the possibility of such damage\&. 
.SH "Function Documentation"
.PP 
.SS "struct nc_session* nc_session_accept_tls (const struct nc_cpblts *capabilities, const char *username, SSL *tls_sess)"

.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
