.TH "model_tree" 3 "Fri Jun 21 2013" "Version 0.5.99" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model_tree \- 
.PP
structure holding information about used data model in YIN format  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <yinparser\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBYIN_TYPE\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char ** \fBkeys\fP"
.br
.ti -1c
.RI "char * \fBns_uri\fP"
.br
.ti -1c
.RI "char * \fBns_prefix\fP"
.br
.ti -1c
.RI "struct \fBmodel_tree\fP * \fBchildren\fP"
.br
.ti -1c
.RI "int \fBkeys_count\fP"
.br
.ti -1c
.RI "int \fBchildren_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure holding information about used data model in YIN format 
.SH "Field Documentation"
.PP 
.SS "\fBYIN_TYPE\fP type"

.SS "char* name"

.SS "char** keys"

.SS "char* ns_uri"

.SS "char* ns_prefix"

.SS "struct \fBmodel_tree\fP* children"

.SS "int keys_count"

.SS "int children_count"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
