.TH "nc_mngmt_server" 3 "Thu Mar 13 2014" "Version 0.7.99" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nc_mngmt_server \- 
.PP
Structure describing a management server where the NETCONF server connects to\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reverse_ssh\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct addrinfo * \fBaddr\fP"
.br
.ti -1c
.RI "struct \fBnc_mngmt_server\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure describing a management server where the NETCONF server connects to\&. 

The structure is public, but, except moving inside the list to specify the server which should be used as first one in nc_session_reverse_connect(), it is HIGHLY recommended to use nc_session_reverse_mngmt_server_*() functions to manipulate with the management servers list\&. 
.SH "Field Documentation"
.PP 
.SS "struct addrinfo* addr"

.SS "struct \fBnc_mngmt_server\fP* next"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
