.TH "src/netconf.h" 3 "Tue Jul 10 2012" "Version 0.1.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/netconf.h \- 
.PP
libnetconf's general public functions and structures definitions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct nc_msg \fBnc_rpc\fP"
.br
.RI "\fIrpc message\&. \fP"
.ti -1c
.RI "typedef struct nc_msg \fBnc_reply\fP"
.br
.RI "\fIreply message\&. \fP"
.ti -1c
.RI "typedef long long unsigned int \fBnc_msgid\fP"
.br
.RI "\fIType representing NETCONF message-id attribute\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNC_REPLY_TYPE\fP { \fBNC_REPLY_UNKNOWN\fP, \fBNC_REPLY_HELLO\fP, \fBNC_REPLY_OK\fP, \fBNC_REPLY_ERROR\fP, \fBNC_REPLY_DATA\fP }"
.br
.RI "\fIEnumeration of <rpc-reply> types\&. \fP"
.ti -1c
.RI "enum \fBNC_RPC_TYPE\fP { \fBNC_RPC_UNKNOWN\fP, \fBNC_RPC_HELLO\fP, \fBNC_RPC_DATASTORE\fP, \fBNC_RPC_SESSION\fP }"
.br
.RI "\fIEnumeration of <rpc> operation types\&. \fP"
.ti -1c
.RI "enum \fBNC_OP\fP { \fBNC_OP_UNKNOWN\fP, \fBNC_OP_GETCONFIG\fP, \fBNC_OP_GET\fP, \fBNC_OP_EDITCONFIG\fP, \fBNC_OP_CLOSESESSION\fP, \fBNC_OP_KILLSESSION\fP, \fBNC_OP_COPYCONFIG\fP, \fBNC_OP_DELETECONFIG\fP, \fBNC_OP_LOCK\fP, \fBNC_OP_UNLOCK\fP }"
.br
.RI "\fIEnumeration of supported <rpc> operations\&. \fP"
.ti -1c
.RI "enum \fBNC_ERR_PARAM\fP { \fBNC_ERR_PARAM_TYPE\fP, \fBNC_ERR_PARAM_TAG\fP, \fBNC_ERR_PARAM_SEVERITY\fP, \fBNC_ERR_PARAM_APPTAG\fP, \fBNC_ERR_PARAM_PATH\fP, \fBNC_ERR_PARAM_MSG\fP, \fBNC_ERR_PARAM_INFO_BADATTR\fP, \fBNC_ERR_PARAM_INFO_BADELEM\fP, \fBNC_ERR_PARAM_INFO_BADNS\fP, \fBNC_ERR_PARAM_INFO_SID\fP }"
.br
.ti -1c
.RI "enum \fBNC_DATASTORE_TYPE\fP { \fBNC_DATASTORE_NONE\fP, \fBNC_DATASTORE_RUNNING\fP, \fBNC_DATASTORE_STARTUP\fP, \fBNC_DATASTORE_CANDIDATE\fP }"
.br
.RI "\fIEnumeration of supported types of datastores defined by NETCONF\&. \fP"
.ti -1c
.RI "enum \fBNC_FILTER_TYPE\fP { \fBNC_FILTER_SUBTREE\fP }"
.br
.RI "\fIEnumeration of supported NETCONF filter types\&. \fP"
.ti -1c
.RI "enum \fBNC_EDIT_OP_TYPE\fP { \fBNC_EDIT_OP_ERROR\fP =  -1, \fBNC_EDIT_OP_MERGE\fP =  1, \fBNC_EDIT_OP_REPLACE\fP =  2, \fBNC_EDIT_OP_CREATE\fP, \fBNC_EDIT_OP_DELETE\fP, \fBNC_EDIT_OP_REMOVE\fP }"
.br
.ti -1c
.RI "enum \fBNC_EDIT_DEFOP_TYPE\fP { \fBNC_EDIT_DEFOP_NONE\fP =  1, \fBNC_EDIT_DEFOP_MERGE\fP =  2, \fBNC_EDIT_DEFOP_REPLACE\fP =  3 }"
.br
.ti -1c
.RI "enum \fBNC_EDIT_ERROPT_TYPE\fP { \fBNC_EDIT_ERROPT_STOP\fP =  1, \fBNC_EDIT_ERROPT_CONT\fP =  2, \fBNC_EDIT_ERROPT_ROLLBACK\fP =  3 }"
.br
.ti -1c
.RI "enum \fBNC_VERB_LEVEL\fP { \fBNC_VERB_ERROR\fP, \fBNC_VERB_WARNING\fP, \fBNC_VERB_VERBOSE\fP, \fBNC_VERB_DEBUG\fP }"
.br
.RI "\fIVerbosity levels\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnc_verbosity\fP (\fBNC_VERB_LEVEL\fP level)"
.br
.RI "\fISet libnetconf's verbosity level\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libnetconf's general public functions and structures definitions\&. 

\fBAuthor:\fP
.RS 4
Radek Krejci rkrejci@cesnet.cz Copyright (C) 2012 CESNET, z\&.s\&.p\&.o\&.
.RE
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of the Company nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
ALTERNATIVELY, provided that this notice is retained in full, this product may be distributed under the terms of the GNU General Public License (GPL) version 2 or later, in which case the provisions of the GPL apply INSTEAD OF those given above\&.
.PP
This software is provided ``as is, and any express or implied warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose are disclaimed\&. In no event shall the company or contributors be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this software, even if advised of the possibility of such damage\&. 
.PP
Definition in file \fBnetconf\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNC_ERR_PARAM\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fINC_ERR_PARAM_TYPE \fP\fP
error-type - The conceptual layer that the error occurred, accepted values include 'transport', 'rpc', 'protocol', 'application'\&. 
.TP
\fB\fINC_ERR_PARAM_TAG \fP\fP
error-tag - Contains a string identifying the error condition\&. 
.TP
\fB\fINC_ERR_PARAM_SEVERITY \fP\fP
error-severity - The error severity, accepted values are 'error' and 'warning'\&. 
.TP
\fB\fINC_ERR_PARAM_APPTAG \fP\fP
error-app-tag - Contains a string identifying the data-model-specific or implementation-specific error condition, if one exists\&. This element will not be present if no appropriate application error-tag can be associated with a particular error condition\&. If a data-model-specific and an implementation-specific error-app-tag both exist, then the data-model-specific value MUST be used by the server\&. 
.TP
\fB\fINC_ERR_PARAM_PATH \fP\fP
error-path - Contains the absolute XPath expression identifying the element path to the node that is associated with the error being reported\&. 
.TP
\fB\fINC_ERR_PARAM_MSG \fP\fP
error-message - A string describing the error\&. 
.TP
\fB\fINC_ERR_PARAM_INFO_BADATTR \fP\fP
bad-attribute in error-info - name of the attribute, contained in 'bad-attribute', 'missing-attribute' and 'unknown-attribute' errors\&. 
.TP
\fB\fINC_ERR_PARAM_INFO_BADELEM \fP\fP
bad-element in error-info - name of the element, contained in 'missing-attribute', bad-attribute', 'unknown-attribute', 'missing-element', 'bad-element', 'unknown-element' and 'unknown-namespace' errors\&. 
.TP
\fB\fINC_ERR_PARAM_INFO_BADNS \fP\fP
bad-namespace in error-info - name of the unexpected namespace, contained in 'unknown-namespace' error\&. 
.TP
\fB\fINC_ERR_PARAM_INFO_SID \fP\fP
session-id in error-info - session ID of session holding the requested lock, contained in 'lock-denied' error\&. 
.PP
Definition at line 121 of file netconf\&.h\&.
.SS "enum \fBNC_EDIT_OP_TYPE\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fINC_EDIT_OP_ERROR \fP\fP
.TP
\fB\fINC_EDIT_OP_MERGE \fP\fP
.TP
\fB\fINC_EDIT_OP_REPLACE \fP\fP
.TP
\fB\fINC_EDIT_OP_CREATE \fP\fP
.TP
\fB\fINC_EDIT_OP_DELETE \fP\fP
.TP
\fB\fINC_EDIT_OP_REMOVE \fP\fP

.PP
Definition at line 200 of file netconf\&.h\&.
.SS "enum \fBNC_EDIT_DEFOP_TYPE\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fINC_EDIT_DEFOP_NONE \fP\fP
.TP
\fB\fINC_EDIT_DEFOP_MERGE \fP\fP
.TP
\fB\fINC_EDIT_DEFOP_REPLACE \fP\fP

.PP
Definition at line 210 of file netconf\&.h\&.
.SS "enum \fBNC_EDIT_ERROPT_TYPE\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fINC_EDIT_ERROPT_STOP \fP\fP
.TP
\fB\fINC_EDIT_ERROPT_CONT \fP\fP
.TP
\fB\fINC_EDIT_ERROPT_ROLLBACK \fP\fP

.PP
Definition at line 216 of file netconf\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
