.TH "NETCONF Event Notifications" 3 "Mon Sep 24 2012" "Version 0.1.4" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NETCONF Event Notifications \- 
.PP
libnetconf's implementation of NETCONF asynchronous message delivery as defined in RFC 5277\&.  

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct nc_msg \fBnc_ntf\fP"
.br
.RI "\fIEvent notification message\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBNC_MSG_TYPE\fP \fBnc_session_recv_notif\fP (struct nc_session *session, \fBnc_ntf\fP **ntf)"
.br
.RI "\fIReceive <notification> message from the specified NETCONF session\&. This function is supposed to be performed only by NETCONF clients\&. \fP"
.ti -1c
.RI "\fBnc_rpc\fP * \fBnc_rpc_subscribe\fP (const char *stream, const struct nc_filter *filter, const time_t *start, const time_t *stop)"
.br
.RI "\fICreate <create-subsciption> NETCONF rpc message\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libnetconf's implementation of NETCONF asynchronous message delivery as defined in RFC 5277\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef struct nc_msg \fBnc_ntf\fP"

.PP
Event notification message\&. 
.PP
Definition at line 61 of file netconf\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBNC_MSG_TYPE\fP nc_session_recv_notif (struct nc_session *session, \fBnc_ntf\fP **ntf)"

.PP
Receive <notification> message from the specified NETCONF session\&. This function is supposed to be performed only by NETCONF clients\&. \fBParameters:\fP
.RS 4
\fIsession\fP NETCONF session to use\&. 
.br
\fIntf\fP Received <notification> message 
.RE
.PP
\fBReturns:\fP
.RS 4
Type of received message\&. NC_MSG_UNKNOWN means error, NC_MSG_NOTIFICATION means that *notif points to the received <notification> message\&. 
.RE
.PP

.SS "\fBnc_rpc\fP* nc_rpc_subscribe (const char *stream, const struct nc_filter *filter, const time_t *start, const time_t *stop)"

.PP
Create <create-subsciption> NETCONF rpc message\&. Detailed description of this operation can be found in RFC 5277, section 2\&.1\&.1\&.
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP Name of the stream of events is of interest\&. Optional parameter (NULL is accepted), if not specified, the default NETCONF stream is subscribed\&. 
.br
\fIfilter\fP Specify the subset of all possible events to be received\&. Optional parameter (NULL is accepted)\&. 
.br
\fIstart\fP Start time to trigger the replay feature from the specified time\&. Optional parameter (NULL is accepted)\&. Format of the date is of type dateTime according to RFC 3339\&. 
.br
\fIstop\fP Stop time to stop the replay of event notifications\&. Optional parameter (NULL is accepted)\&. Format of the date is of type dateTime according to RFC 3339\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Created rpc message\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
