.TH "ns_pair" 3 "Fri Apr 15 2016" "Version 0.10.0-146_trunk" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ns_pair \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transapi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBhref\fP"
.br
.ti -1c
.RI "const char * \fBprefix\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const char* href"

.SS "const char* prefix"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
