.TH "Datastore operations" 3 "Sat May 5 2012" "Version 0.1.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Datastore operations \- 
.PP
libnetconf's functions for handling NETCONF datastores'\&.  

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNC_DATASTORE_TYPE\fP { \fBNC_DATASTORE_NONE\fP, \fBNC_DATASTORE_RUNNING\fP, \fBNC_DATASTORE_STARTUP\fP, \fBNC_DATASTORE_CANDIDATE\fP }"
.br
.RI "\fIEnumeration of supported types of datastores defined by NETCONF'\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libnetconf's functions for handling NETCONF datastores'\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNC_DATASTORE_TYPE\fP"
.PP
Enumeration of supported types of datastores defined by NETCONF'\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fINC_DATASTORE_NONE \fP\fP
value describing that no datastore was selected, (usage similar to NULL) 
.TP
\fB\fINC_DATASTORE_RUNNING \fP\fP
base NETCONF's datastore containing current device configuration 
.TP
\fB\fINC_DATASTORE_STARTUP \fP\fP
separated startup datastore as defined in Distinct Startup Capability 
.TP
\fB\fINC_DATASTORE_CANDIDATE \fP\fP
separated working datastore as defined in Candidate Configuration Capability 
.PP
Definition at line 96 of file netconf\&.h'\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code'\&.
