.TH "todo" 3 "Wed Jul 11 2012" "Version 0.1.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.IP "\fBGlobal \fBncds_file_set_path\fP (struct ncds_ds *datastore, char *path)\fP" 1c
Implement \fBncds_file_set_path()\fP 
.IP "\fBGlobal \fBncds_free\fP (struct ncds_ds *datastore)\fP" 1c
Implement \fBncds_free()\fP 
.IP "\fBGlobal \fBncds_init\fP (struct ncds_ds *datastore)\fP" 1c
Implement \fBncds_init()\fP
.PP
Specify error codes for indicating the problem 
.PP

