.TH "todo" 3 "Thu Feb 6 2014" "Version 0.7.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBGlobal \fBncntf_stream_iter_finish\fP (const char *stream)\fP" 1c
: thread safety (?thread-specific variables)
.PP
.IP "\fBGlobal \fBncntf_stream_iter_next\fP (const char *stream, time_t start, time_t stop, time_t *event_time)\fP" 1c
: thread safety (?thread-specific variables)
.PP
.IP "\fBGlobal \fBncntf_stream_iter_start\fP (const char *stream)\fP" 1c
: thread safety (?thread-specific variables)
.PP
.PP

