.TH "todo" 3 "Tue Sep 25 2012" "Version 0.2.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.IP "\fBGlobal \fBnc_ntf_dispatch\fP (struct nc_session *session, const nc_rpc *subscribe_rpc)\fP" 1c
Implement this function\&.
.PP
.IP "\fBGlobal \fBnc_ntf_event_new\fP (char *stream, time_t etime, NC_NTF_EVENT event,\&.\&.\&.)\fP" 1c
Implement this function\&.  
.IP "\fBGlobal \fBNCDS_TYPE_EMPTY\fP \fP" 1c
Implement functions  
.IP "\fBpage \fBNETCONF library - libnetconf\fP \fP" 1c
some common function to performi this type of requests will be added\&.
.br
.PP

