.TH "transapi_data_clbcks" 3 "Mon Aug 12 2013" "Version 0.5.99" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transapi_data_clbcks \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transapi_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBtransapi_data_callbacks\fP * \fBdata_clbks\fP"
.br
.ti -1c
.RI "struct 
.br
\fBtransapi_xml_data_callbacks\fP * \fBdata_clbks_xml\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBtransapi_data_callbacks\fP* data_clbks"

.SS "struct \fBtransapi_xml_data_callbacks\fP* data_clbks_xml"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
