.TH "transapi_rpc_callbacks" 3 "Mon Apr 29 2013" "Version 0.5.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transapi_rpc_callbacks \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transapi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcallbacks_count\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   char * \fBname\fP"
.br
.ti -1c
.RI "   int \fBarg_count\fP"
.br
.ti -1c
.RI "   \fBnc_reply\fP *(* \fBfunc\fP )()"
.br
.ti -1c
.RI "   char * \fBarg_order\fP [MAX_RPC_INPUT_ARGS]"
.br
.ti -1c
.RI "} \fBcallbacks\fP []"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int callbacks_count"

.SS "char* name"

.SS "int arg_count"

.SS "\fBnc_reply\fP*(* func)()"

.SS "char* arg_order[MAX_RPC_INPUT_ARGS]"

.SS "struct { \&.\&.\&. }   callbacks[]"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
