.TH "transapi_file_callbacks" 3 "Fri Apr 15 2016" "Version 0.10.0-146_trunk" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transapi_file_callbacks \- 
.PP
Functions to call if the specified file is modified\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transapi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int(* \fBfunc\fP )(const char *, xmlDocPtr *, int *)"
.br
.ti -1c
.RI "   const char * \fBpath\fP"
.br
.ti -1c
.RI "} \fBcallbacks\fP []"
.br
.ti -1c
.RI "int \fBcallbacks_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to call if the specified file is modified\&. 

Description of the callback parameters: const char *filename[in] - name of the changed file xmlDocPtr *edit_config[out] - return parameter with edit-config data to to change running datastore\&. The data are supposed to be enclosed in <config/> root element\&. 
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. }   callbacks[]"

.SS "int callbacks_count"

.SS "int(* func)(const char *, xmlDocPtr *, int *)"

.SS "const char* path"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
