.TH "transapi_init" 3 "Mon May 6 2013" "Version 0.5.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transapi_init \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transapi_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xmlDocPtr(* \fBinit_xml\fP )(xmlDocPtr startup_config)"
.br
.ti -1c
.RI "char *(* \fBinit\fP )(char *startup_config)"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "xmlDocPtr(* init_xml)(xmlDocPtr startup_config)"

.SS "char*(* init)(char *startup_config)"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
