.TH "transapi_rpc_clbcks" 3 "Mon Aug 12 2013" "Version 0.5.99" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transapi_rpc_clbcks \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transapi_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBtransapi_rpc_callbacks\fP * \fBrpc_clbks\fP"
.br
.ti -1c
.RI "struct \fBtransapi_xml_rpc_callbacks\fP * \fBrpc_clbks_xml\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBtransapi_rpc_callbacks\fP* rpc_clbks"

.SS "struct \fBtransapi_xml_rpc_callbacks\fP* rpc_clbks_xml"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
