.TH "transapi_rpc_callbacks" 3 "Fri Apr 15 2016" "Version 0.10.0-146_trunk" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transapi_rpc_callbacks \- 
.PP
Same as \fBtransapi_rpc_callbacks\fP\&. Using libxml2 structures for callbacks parameters\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transapi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBnc_reply\fP *(* \fBfunc\fP )(xmlNodePtr)"
.br
.ti -1c
.RI "   char * \fBname\fP"
.br
.ti -1c
.RI "} \fBcallbacks\fP []"
.br
.ti -1c
.RI "int \fBcallbacks_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Same as \fBtransapi_rpc_callbacks\fP\&. Using libxml2 structures for callbacks parameters\&. 
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. }   callbacks[]"

.SS "int callbacks_count"

.SS "\fBnc_reply\fP*(* func)(xmlNodePtr)"

.SS "char* name"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
