.TH "transapi" 3 "Mon Apr 29 2013" "Version 0.5.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transapi \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transapi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBmodule\fP"
.br
.RI "\fILoaded shared library with transapi callbacks\&. \fP"
.ti -1c
.RI "struct \fBtransapi_data_callbacks\fP * \fBdata_clbks\fP"
.br
.RI "\fITransapi callback mapping structure\&. \fP"
.ti -1c
.RI "struct \fBtransapi_rpc_callbacks\fP * \fBrpc_clbks\fP"
.br
.RI "\fITransapi rpc callbacks mapping structure\&. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* module"

.PP
Loaded shared library with transapi callbacks\&. 
.SS "struct \fBtransapi_data_callbacks\fP* data_clbks"

.PP
Transapi callback mapping structure\&. 
.SS "struct \fBtransapi_rpc_callbacks\fP* rpc_clbks"

.PP
Transapi rpc callbacks mapping structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
