.TH "transapi_data_callbacks" 3 "Thu Feb 6 2014" "Version 0.7.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transapi_data_callbacks \- 
.PP
Same as \fBtransapi_data_callbacks\fP\&. Using libxml2 structures for callbacks parameters\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transapi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int(* \fBfunc\fP )(void **, \fBXMLDIFF_OP\fP, 
.br
      xmlNodePtr, struct nc_err **)"
.br
.ti -1c
.RI "   char * \fBpath\fP"
.br
.ti -1c
.RI "} \fBcallbacks\fP []"
.br
.ti -1c
.RI "int \fBcallbacks_count\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Same as \fBtransapi_data_callbacks\fP\&. Using libxml2 structures for callbacks parameters\&. 
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. }   callbacks[]"

.SS "int callbacks_count"

.SS "void* data"

.SS "int(* func)(void **, \fBXMLDIFF_OP\fP, xmlNodePtr, struct nc_err **)"

.SS "char* path"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
