.TH "troubles" 3 "Fri Apr 15 2016" "Version 0.10.0-146_trunk" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
troubles \- Troubleshooting 
Since libnetconf shares some resources (statistics, datastores,\&.\&.\&.) among all its instances, various locks usage is necessary\&. During the development, crashes of an application is very usual\&. And ometimes, such a crash can happen during a critical section in libnetconf\&. Then, some of the locks used by libnetconf can stay unlocked so a consequent call to a libnetconf function can cause application freeze\&. To recover from this state, a developer has to manually unlock the locks removing the following files\&.
.IP "\(bu" 2
/dev/shm/sem\&.NCDS_FLOCK_*
.IP "\(bu" 2
/var/lib/libnetconf/libnetconf_sessions\&.bin
.PP
.PP
Note that before removing the locks manually, all applications using libnetconf should be stopped\&. 
