.TH "src/url.h" 3 "Thu Feb 6 2014" "Version 0.7.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/url.h \- 
.PP
libnetconf's public API to use the URL capability\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNC_URL_PROTOCOLS\fP { \fBNC_URL_UNKNOWN\fP = 0, \fBNC_URL_SCP\fP = 1, \fBNC_URL_HTTP\fP = 2, \fBNC_URL_HTTPS\fP = 4, \fBNC_URL_FTP\fP = 8, \fBNC_URL_SFTP\fP = 16, \fBNC_URL_FTPS\fP = 32, \fBNC_URL_FILE\fP = 64, \fBNC_URL_ALL\fP = 127 }"
.br
.RI "\fIList of protocol IDs supported by URL capability implementation\&. Values are used to enable/disable server support of these protocols (\fBnc_url_enable()\fP, \fBnc_url_disable()\fP)\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnc_url_disable\fP (\fBNC_URL_PROTOCOLS\fP protocol)"
.br
.RI "\fIDisable specific protocol for use in URL capability\&. \fP"
.ti -1c
.RI "void \fBnc_url_enable\fP (\fBNC_URL_PROTOCOLS\fP protocol)"
.br
.RI "\fIEnable specific protocol for use in URL capability\&. \fP"
.ti -1c
.RI "void \fBnc_url_set_protocols\fP (int protocols)"
.br
.RI "\fIOverwrite enabled protocols for URL capability\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libnetconf's public API to use the URL capability\&. 


.PP
\fBAuthor:\fP
.RS 4
Ondrej Vlk ondrasek.vlk@gmail.com Copyright (c) 2012-2014 CESNET, z\&.s\&.p\&.o\&.
.RE
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of the Company nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
ALTERNATIVELY, provided that this notice is retained in full, this product may be distributed under the terms of the GNU General Public License (GPL) version 2 or later, in which case the provisions of the GPL apply INSTEAD OF those given above\&.
.PP
This software is provided ``as is, and any express or implied warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose are disclaimed\&. In no event shall the company or contributors be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this software, even if advised of the possibility of such damage\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
