.TH "usage" 3 "Thu Feb 6 2014" "Version 0.7.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usage \- Using libnetconf 
Useful notes on using the libnetconf library can be found in the following articles\&. However, the source codes of the example applications in the \fCNetopeer project\fP are supposed to be the most accurate, up-to-date and generally the best source of information\&.
.PP
.IP "\(bu" 2
\fBClient\fP
.IP "\(bu" 2
\fBServer\fP
.PP
.PP
.SS "GLOSSARY "
.PP
.IP "\(bu" 2
\fBmessage\fP - all the types of messages passing through NETCONF\&. It includes rpc, rpc-reply and notification\&. 
.PP

