.TH "src/with_defaults.h" 3 "Thu Feb 6 2014" "Version 0.7.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/with_defaults.h \- 
.PP
Implementation of NETCONF's with-defaults capability defined in RFC 6243\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'netconf\&.h'\fP
.br
\fC#include 'messages\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNCDFLT_DISABLE\fP   \fBncdflt_set_basic_mode\fP(NCWD_MODE_DISABLED)"
.br
.RI "\fIDisable support for the with-defaults capability\&. This can be done on either a client or a server\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBNCWD_MODE\fP \fBncdflt_get_basic_mode\fP (void)"
.br
.RI "\fIGet the current set basic mode of the with-defaults capability\&. \fP"
.ti -1c
.RI "\fBNCWD_MODE\fP \fBncdflt_get_supported\fP (void)"
.br
.RI "\fIGet ORed value containing the currently supported with-defaults modes\&. \fP"
.ti -1c
.RI "\fBNCWD_MODE\fP \fBncdflt_rpc_get_withdefaults\fP (const \fBnc_rpc\fP *rpc)"
.br
.RI "\fIGet value of the <with-defaults> element from the rpc message\&. \fP"
.ti -1c
.RI "void \fBncdflt_set_basic_mode\fP (\fBNCWD_MODE\fP mode)"
.br
.RI "\fISet the basic mode of the with-defaults capability for a NETCONF server\&. \fP"
.ti -1c
.RI "void \fBncdflt_set_supported\fP (\fBNCWD_MODE\fP modes)"
.br
.RI "\fISet with-defaults modes that are supported\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of NETCONF's with-defaults capability defined in RFC 6243\&. 


.PP
\fBAuthor:\fP
.RS 4
Radek Krejci rkrejci@cesnet.cz Copyright (c) 2012-2014 CESNET, z\&.s\&.p\&.o\&.
.RE
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of the Company nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
ALTERNATIVELY, provided that this notice is retained in full, this product may be distributed under the terms of the GNU General Public License (GPL) version 2 or later, in which case the provisions of the GPL apply INSTEAD OF those given above\&.
.PP
This software is provided ``as is, and any express or implied warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose are disclaimed\&. In no event shall the company or contributors be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this software, even if advised of the possibility of such damage\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
