.TH "With-defaults capability" 3 "Thu Feb 6 2014" "Version 0.7.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
With-defaults capability \- 
.PP
libnetconf's settings for NETCONF :with-defaults capability as defined in RFC 6243\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNCDFLT_DISABLE\fP   \fBncdflt_set_basic_mode\fP(NCWD_MODE_DISABLED)"
.br
.RI "\fIDisable support for the with-defaults capability\&. This can be done on either a client or a server\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNCWD_MODE\fP { \fBNCWD_MODE_NOTSET\fP = 0, \fBNCWD_MODE_ALL\fP = 1, \fBNCWD_MODE_TRIM\fP = 2, \fBNCWD_MODE_EXPLICIT\fP = 4, \fBNCWD_MODE_ALL_TAGGED\fP = 8 }"
.br
.RI "\fIEnumeration of <with-defaults> element values\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBNCWD_MODE\fP \fBncdflt_get_basic_mode\fP (void)"
.br
.RI "\fIGet the current set basic mode of the with-defaults capability\&. \fP"
.ti -1c
.RI "\fBNCWD_MODE\fP \fBncdflt_get_supported\fP (void)"
.br
.RI "\fIGet ORed value containing the currently supported with-defaults modes\&. \fP"
.ti -1c
.RI "\fBNCWD_MODE\fP \fBncdflt_rpc_get_withdefaults\fP (const \fBnc_rpc\fP *rpc)"
.br
.RI "\fIGet value of the <with-defaults> element from the rpc message\&. \fP"
.ti -1c
.RI "void \fBncdflt_set_basic_mode\fP (\fBNCWD_MODE\fP mode)"
.br
.RI "\fISet the basic mode of the with-defaults capability for a NETCONF server\&. \fP"
.ti -1c
.RI "void \fBncdflt_set_supported\fP (\fBNCWD_MODE\fP modes)"
.br
.RI "\fISet with-defaults modes that are supported\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libnetconf's settings for NETCONF :with-defaults capability as defined in RFC 6243\&. 

libnetconf's implementation of NETCONF with-defaults capability as defined in RFC 6243\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define NCDFLT_DISABLE   \fBncdflt_set_basic_mode\fP(NCWD_MODE_DISABLED)"

.PP
Disable support for the with-defaults capability\&. This can be done on either a client or a server\&. This is an alternative for ncdflt_set_basic_mode(NCDFLT_MODE_DISABLED)\&. To enable the with-defaults capability, use \fBncdflt_set_basic_mode()\fP to set the with-defaults' basic mode\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNCWD_MODE\fP"

.PP
Enumeration of <with-defaults> element values\&. Valid only with enabled :with-defaults capability 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINCWD_MODE_NOTSET \fP\fP
follow NETCONF defined default behavior (mode selected by server as its basic mode) 
.TP
\fB\fINCWD_MODE_ALL \fP\fP
report-all mode (RFC 6243, sec\&. 3\&.1) 
.TP
\fB\fINCWD_MODE_TRIM \fP\fP
trim mode (RFC 6243, sec\&. 3\&.2) 
.TP
\fB\fINCWD_MODE_EXPLICIT \fP\fP
explicit mode (RFC 6243, sec\&. 3\&.3) 
.TP
\fB\fINCWD_MODE_ALL_TAGGED \fP\fP
report-all-tagged mode (RFC 6243, sec\&. 3\&.4) 
.SH "Function Documentation"
.PP 
.SS "\fBNCWD_MODE\fP ncdflt_get_basic_mode (void)"

.PP
Get the current set basic mode of the with-defaults capability\&. 
.PP
\fBReturns:\fP
.RS 4
Current value of the with-defaults' basic mode\&. 
.RE
.PP

.SS "\fBNCWD_MODE\fP ncdflt_get_supported (void)"

.PP
Get ORed value containing the currently supported with-defaults modes\&. 
.PP
\fBReturns:\fP
.RS 4
ORed value containing the currently supported with-defaults modes\&. 
.RE
.PP

.SS "\fBNCWD_MODE\fP ncdflt_rpc_get_withdefaults (const \fBnc_rpc\fP *rpc)"

.PP
Get value of the <with-defaults> element from the rpc message\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrpc\fP RPC message to be parsed\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
with-defaults mode of the NETCONF rpc message\&. 
.RE
.PP

.SS "void ncdflt_set_basic_mode (\fBNCWD_MODE\fPmode)"

.PP
Set the basic mode of the with-defaults capability for a NETCONF server\&. The default basic mode used by libnetconf is 'explicit'\&. This function should be used before establishing a NETCONF session to settle on a common set of capabilities between a client and a server\&.
.PP
On the client side, this function does not have any effect of setting up a specific mode\&. It only disables (NCDFLT_MODE_DISABLED) or enables (any other valid value) support for the with-defaults capability\&.
.PP
\fBParameters:\fP
.RS 4
\fImode\fP One of the with-defaults capability basic modes, NCDFLT_MODE_ALL_TAGGED is not a basic mode and such value is ignored\&. 
.RE
.PP

.SS "void ncdflt_set_supported (\fBNCWD_MODE\fPmodes)"

.PP
Set with-defaults modes that are supported\&. This function should be used before establishing a NETCONF session to settle on a common set of capabilities between a client and a server\&. On the client side, this function has no effect\&.
.PP
\fBParameters:\fP
.RS 4
\fImodes\fP ORed set of the supported NCDFLT_MODE modes\&. The basic mode is always supported automatically\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
