.TH "src/transapi/xmldiff.h" 3 "Mon Sep 2 2013" "Version 0.5.99" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/transapi/xmldiff.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <libxml/tree\&.h>\fP
.br
\fC#include 'yinparser\&.h'\fP
.br
\fC#include 'transapi\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBxmldiff_entry\fP"
.br
.RI "\fIstructure for single diff entry \fP"
.ti -1c
.RI "struct \fBxmldiff\fP"
.br
.RI "\fIstructure holding all differencies found in compared files \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBxmldiff_free\fP (struct \fBxmldiff\fP *diff)"
.br
.RI "\fIDestroy and free whole xmldiff structure\&. \fP"
.ti -1c
.RI "struct \fBxmldiff\fP * \fBxmldiff_diff\fP (xmlDocPtr old, xmlDocPtr new, struct \fBmodel_tree\fP *model, const char *ns_mapping[])"
.br
.RI "\fIModule top level function\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
