.TH "xmldiff" 3 "Fri Jun 7 2013" "Version 0.5.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xmldiff \- 
.PP
structure holding all differencies found in compared files  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xmldiff\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBxmldiff_entry\fP * \fBdiff_list\fP"
.br
.ti -1c
.RI "int \fBdiff_count\fP"
.br
.ti -1c
.RI "int \fBdiff_alloc\fP"
.br
.ti -1c
.RI "\fBXMLDIFF_OP\fP \fBall_stat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure holding all differencies found in compared files 
.SH "Field Documentation"
.PP 
.SS "struct \fBxmldiff_entry\fP* diff_list"

.SS "int diff_count"

.SS "int diff_alloc"

.SS "\fBXMLDIFF_OP\fP all_stat"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
