.TH "xmldiff_entry" 3 "Thu Jun 13 2013" "Version 0.5.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xmldiff_entry \- 
.PP
structure for single diff entry  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xmldiff\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "xmlNodePtr \fBnode\fP"
.br
.ti -1c
.RI "\fBXMLDIFF_OP\fP \fBop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure for single diff entry 
.SH "Field Documentation"
.PP 
.SS "char* path"

.SS "xmlNodePtr node"

.SS "\fBXMLDIFF_OP\fP op"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
