.TH "yinmodel" 3 "Wed Apr 3 2013" "Version 0.4.0" "libnetconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yinmodel \- 
.PP
structure holding information needed for xml document comparsion  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <yinparser\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBYIN_TYPE\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char ** \fBkeys\fP"
.br
.ti -1c
.RI "char * \fBns_uri\fP"
.br
.ti -1c
.RI "struct \fByinmodel\fP * \fBchildren\fP"
.br
.ti -1c
.RI "int \fBkeys_count\fP"
.br
.ti -1c
.RI "int \fBchildren_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure holding information needed for xml document comparsion 
.SH "Field Documentation"
.PP 
.SS "\fBYIN_TYPE\fP type"

.SS "char* name"

.SS "char** keys"

.SS "char* ns_uri"

.SS "struct \fByinmodel\fP* children"

.SS "int keys_count"

.SS "int children_count"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnetconf from the source code\&.
